export const testimonialService_dummy = [
  {
    review: `Bhupendra Singh and the Robotronix team were extremely professional and collaborative throughout the project. Communication was consistent and proactive, with daily updates and regular feedback loops to ensure alignment. They were flexible and readily available for impromptu calls whenever clarifications were needed. The team stayed closely engaged while completing each milestone, actively seeking approvals to ensure we were always on the same page. The final MVP delivered met all expectations outlined at the start of the contract and provided a strong, reliable foundation for our product.`,
    clientName: "Srijit Banerjee",
    designation: "Engineer for LLM Integration and Backend Development",
    companyName: "Upwork Client",
    rating: 5,
    isActive: true,
  },
  {
    review: `Overall experience with them was good.`,
    clientName: "Prathish Vijay - CEO",
    designation: "AI/ML Engineer – Short-Term Contract",
    companyName: " Phykon",
    rating: 5,
    isActive: true,
  },
  {
    review: `They are good at what they do and were quick to understand the terminologies and were able to turn around a quick V1 for us. Hoping to work with them soon.`,
    clientName: "Rishabh Raghavender",
    designation: "LLM Specialist – Manufacturing Query Tool",
    companyName: "Zetwerk",
    rating: 5,
    isActive: true,
  },
  {
    review: `Their dedication and proper allocation of resources were good.`,
    clientName: "Gaurav Nema - CEO",
    designation: "AI Development Project",
    companyName: "InnoBimb Infotech Pvt. Ltd.",
    rating: 5,
    isActive: true,
  },
  {
    review: `Their proactive communication, commitment to quality, and ability to adapt to our evolving needs are truly impressive.`,
    clientName: "Saurabh Prakash - Partner",
    designation: "AI Development Project",
    companyName: "Mobitra Technologies Private Limited",
    rating: 5,
    isActive: true,
  },
  {
    review: `One of the best team i have worked with so far. They are very professional, and i got the reports before time. Great experience in visualization / PowerBi. Highly Recommended`,
    clientName: "Ambuj Shukla",
    designation: "",
    companyName: "Upwork Client",
    rating: 5,
    isActive: true,
  },
  {
    review: `Robotronix showed great project management skills.`,
    clientName: "Kapil Gupta - Manager",
    designation: "AI & Robotics Process Automation",
    companyName: "ReNew Pvt Ltd",
    rating: 5,
    isActive: true,
  },
  {
    review: `Their crystal-clear communication and strong commitment stood out the most.`,
    clientName: "Jatin Puri - Managing Director",
    designation: "Web Dev & SEO Project",
    companyName: "Color Drop Business Solutions",
    rating: 5,
    isActive: true,
  },
  {
    review: `Robotronix excels in providing innovative, reliable, and customized technology solutions to businesses of all sizes.`,
    clientName: "Ashish Shrivastava - CTO",
    designation: "Web Design, Development & Deployment",
    companyName: "Opulence Infotech Pvt. Ltd.",
    rating: 5,
    isActive: true,
  },
  {
    review: `Their ability to tackle complex challenges with a structured and solution-oriented approach was impressive.`,
    clientName: "Sunil Pandey - Marketing Head",
    designation: "Object Detection Model Development",
    companyName: "Evolve IT Solutions Pvt Ltd",
    rating: 5,
    isActive: true,
  },
];
